[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/vertexai" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-vertexai"
version = "0.11.1"
description = "OpenTelemetry Vertex AI instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>",
  "Swaroop <maddisaiswaroop@gmail.com>"
]
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/vertexai"

[tool.poetry.dependencies]
python = ">=3.8.1,<4"
opentelemetry-api = "^1.22.0"
opentelemetry-instrumentation = "0.43b0"
opentelemetry-semantic-conventions-ai = "^0.0.20"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "7.0.0"
pytest = "7.4.4"
pytest-sugar = "0.9.7"

[tool.poetry.group.test.dependencies]
pytest = "7.4.4"
pytest-sugar = "0.9.7"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
opentelemetry-sdk = "^1.22.0"
google-cloud-aiplatform = "^1.39.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
