[tool.coverage.run]
branch = true
source = ["opentelemetry/instrumentation/vertexai"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-vertexai"
version = "0.50.1"
description = "OpenTelemetry Vertex AI instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>",
  "Swaroop <maddisaiswaroop@gmail.com>",
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-vertexai"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/vertexai"

[tool.poetry.dependencies]
python = ">=3.10,<4"
opentelemetry-api = "^1.38.0"
opentelemetry-instrumentation = ">=0.59b0"
opentelemetry-semantic-conventions = ">=0.59b0"
opentelemetry-semantic-conventions-ai = "^0.4.13"
urllib3 = "^2.5.0"
requests = "^2.32.4"
protobuf = "^5.29.5"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.0.0"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
vcrpy = { git = "https://github.com/kevin1024/vcrpy.git", branch = "master" }
pytest-recording = "^0.13.1"
pytest-asyncio = "^0.23.7"
opentelemetry-sdk = "^1.38.0"
google-cloud-aiplatform = "^1.54.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["google-cloud-aiplatform"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
google_cloud_aiplatform = "opentelemetry.instrumentation.vertexai:VertexAIInstrumentor"

[tool.pytest.ini_options]
asyncio_mode = "auto"
