version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-anthropic"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-anthropic"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-bedrock"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-bedrock"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-cassio"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-cassio"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-chromadb"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-chromadb"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-cohere"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-cohere"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-haystack"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-haystack"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-langchain"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-langchain"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-llamaindex"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-llamaindex"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-openai"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-openai"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-pinecone"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-pinecone"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-qdrant"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-qdrant"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-replicate"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-replicate"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-transformers"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-transformers"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-vertexai"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-vertexai"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-watsonx"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-watsonx"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-instrumentation-weaviate"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-instrumentation-weaviate"
  - package-ecosystem: "pip"
    directory: "/packages/opentelemetry-semantic-conventions-llm"
    schedule:
      interval: "weekly"
    labels:
      - "opentelemetry-semantic-conventions-llm"
  - package-ecosystem: "pip"
    directory: "/packages/traceloop-sdk"
    schedule:
      interval: "weekly"
    labels:
      - "traceloop-sdk"
