[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/qdrant" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-qdrant"
version = "0.24.0"
description = "OpenTelemetry Qdrant instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-qdrant"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/qdrant"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.25.0"
opentelemetry-instrumentation = "^0.46b0"
opentelemetry-semantic-conventions = "^0.46b0"
opentelemetry-semantic-conventions-ai = "0.3.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.0.0"

[tool.poetry.group.test.dependencies]
qdrant-client = "^1.9.1"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
opentelemetry-sdk = "^1.23.0"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["qdrant-client"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
qdrant_client = "opentelemetry.instrumentation.qdrant:QdrantInstrumentor"
