[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/bedrock" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-bedrock"
version = "0.15.7"
description = "OpenTelemetry Bedrock instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-bedrock"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/bedrock"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.23.0"
opentelemetry-instrumentation = "0.44b0"
opentelemetry-semantic-conventions = "0.44b0"
opentelemetry-semantic-conventions-ai = "^0.1.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.1.0"
flake8 = "7.0.0"
pytest = "8.1.0"
pytest-sugar = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
