[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/openai" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-openai"
version = "0.17.3"
description = "OpenTelemetry OpenAI instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-openai"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/openai"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.24.0"
opentelemetry-instrumentation = "^0.45b0"
opentelemetry-semantic-conventions = "^0.45b0"
opentelemetry-semantic-conventions-ai = "0.2.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.1.0"
flake8 = "7.0.0"

[tool.poetry.group.test.dependencies]
pytest = "8.1.1"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
openai = {extras = ["datalib"], version = "^1.14.2"}
opentelemetry-sdk = "^1.23.0"
pytest-asyncio = "^0.23.5"
tiktoken = "^0.6.0"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["openai"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
openai = "opentelemetry.instrumentation.openai:OpenAIInstrumentor"
