[tool.coverage.run]
branch = true
source = ["opentelemetry/instrumentation/openai_agents"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-openai-agents"
version = "0.46.0"
description = "OpenTelemetry OpenAI Agents instrumentation"
authors = ["Gal Kleinman <gal@traceloop.com>", "Nir Gazit <nir@traceloop.com>"]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-openai-agents"
license = "Apache-2.0"
readme = "README.md"


[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/openai_agents"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.28.0"
opentelemetry-instrumentation = ">=0.50b0"
opentelemetry-semantic-conventions = ">=0.50b0"
opentelemetry-semantic-conventions-ai = "^0.4.13"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.1.1"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
pytest-recording = "^0.13.1"
vcrpy = "^6.0.1"
pytest-asyncio = "^1.0.0"
litellm = "^1.71.2"
opentelemetry-sdk = "^1.27.0"
openai-agents = "^0.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["openai_agents"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
openai_agents = "opentelemetry.instrumentation.openai_agents:OpenAIAgentsInstrumentor"
