[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/weaviate" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-weaviate"
version = "0.12.4"
description = "OpenTelemetry Weaviate instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/weaviate"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
opentelemetry-api = "^1.23.0"
opentelemetry-instrumentation = "0.44b0"
opentelemetry-semantic-conventions-ai = "^0.0.20"
weaviate-client = "^3.26.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "7.0.0"
pytest = "8.0.2"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
openai = "^1.12.0"
pytest = "8.0.2"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
opentelemetry-sdk = "^1.22.0"
opentelemetry-instrumentation-openai = {path="../opentelemetry-instrumentation-openai", develop=true}
weaviate-client = "^3.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
