[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/chromadb" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-chromadb"
version = "0.12.1"
description = "OpenTelemetry Chroma DB instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/chromadb"

[tool.poetry.dependencies]
python = ">=3.8.1,<4"
opentelemetry-api = "^1.22.0"
opentelemetry-semantic-conventions = "0.43b0"
opentelemetry-instrumentation = "0.43b0"
opentelemetry-semantic-conventions-ai = "^0.0.20"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "7.0.0"
pytest = "8.0.1"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
chromadb = "^0.4.22"
pytest = "8.0.1"
pytest-sugar = "1.0.0"
opentelemetry-sdk = "^1.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
