[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/haystack" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../coverage/packages/opentelemetry-instrumentation-haystack/html' --cov-report xml:'../../coverage/packages/opentelemetry-instrumentation-cohere/coverage.xml' --html='../../reports/packages/opentelemetry-instrumentation-cohere/unittests/html/index.html' --junitxml='../../reports/packages/opentelemetry-instrumentation-cohere/unittests/junit.xml'"

[tool.poetry]
name = "opentelemetry-instrumentation-haystack"
version = "0.0.3"
description = "OpenTelemetry Haystack instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/haystack"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
opentelemetry-api = "^1.19.0"
opentelemetry-instrumentation = "^0.40b0"
opentelemetry-semantic-conventions-ai = "^0.0.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "6.1.0"
pytest = "7.4.1"
pytest-sugar = "0.9.7"
pytest-cov = "4.1.0"
pytest-html = "4.0.0"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "opentelemetry-instrumentation-haystack_v$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
