[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/haystack" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-haystack"
version = "0.14.0"
description = "OpenTelemetry Haystack instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>"
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-haystack"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/haystack"

[tool.poetry.dependencies]
python = ">=3.8.1,<4"
opentelemetry-api = "^1.23.0"
opentelemetry-instrumentation = "0.44b0"
opentelemetry-semantic-conventions-ai = "^0.0.23"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "7.0.0"
pytest = "8.1.0"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
farm-haystack = "~1.20.1"
pytest = "8.1.0"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
opentelemetry-sdk = "^1.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.entry-points.opentelemetry_instrumentor]
haystack = "opentelemetry.instrumentation.haystack:HaystackInstrumentor"
