[tool.coverage.run]
branch = true
source = ["opentelemetry/instrumentation/transformers"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-transformers"
version = "0.42.0"
description = "OpenTelemetry transformers instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>",
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-transformers"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/transformers"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.35.0"
opentelemetry-instrumentation = ">=0.50b0"
opentelemetry-semantic-conventions = ">=0.50b0"
opentelemetry-semantic-conventions-ai = "0.4.11"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.3.1"
flake8 = "7.1.2"
pytest = "^8.3.3"
pytest-sugar = "1.0.0"
tensorflow = "^2.19.0"
transformers = "^4.51.3"
tf-keras = "^2.19.0"
torch = "^2.7.0"
opentelemetry-sdk = "^1.35.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
