[tool.poetry]
name = "opentelemetry-instrumentation-watsonx"
version = "0.17.3"
description = "OpenTelemetry IBM Watsonx Instrumentation"
authors = ["Guangya Liu <gyliu@ibm.com>"]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-watsonx"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/watsonx"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.24.0"
opentelemetry-instrumentation = "^0.45b0"
opentelemetry-semantic-conventions = "^0.45b0"
opentelemetry-semantic-conventions-ai = "0.2.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.1.0"
flake8 = "7.0.0"
pytest = "8.1.1"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "8.1.1"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
opentelemetry-sdk = "^1.23.0"
pytest-asyncio = "^0.23.5"
ibm-watson-machine-learning = "1.0.333"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["ibm-watson-machine-learning"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
ibm-watson-machine-learning = "opentelemetry.instrumentation.watsonx:WatsonxInstrumentor"
