[tool.poetry]
name = "opentelemetry-instrumentation-watsonx"
version = "0.12.3"
description = "OpenTelemetry IBM Watsonx Instrumentation"
authors = ["Guangya Liu <gyliu@ibm.com>"]
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/watsonx"

[tool.poetry.dependencies]
python = ">=3.10,<4"
opentelemetry-api = "^1.22.0"
opentelemetry-instrumentation = "0.43b0"
opentelemetry-semantic-conventions-ai = "^0.0.20"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.4"
flake8 = "7.0.0"
pytest = "8.0.1"
pytest-sugar = "1.0.0"
ibm-watsonx-ai = "^0.1.4"
ibm-watson-machine-learning = "1.0.347"

[tool.poetry.group.test.dependencies]
pytest = "8.0.1"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
ibm-watsonx-ai = "^0.1.4"
ibm-watson-machine-learning = "1.0.347"
opentelemetry-sdk = "^1.22.0"
pytest-asyncio = "^0.23.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
