[tool.coverage.run]
branch = true
source = ["opentelemetry/instrumentation/writer"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-writer"
version = "0.50.1"
description = "OpenTelemetry Writer instrumentation"
authors = ["Yan Tolstoy <yan.talstoi@writer.com>", "Writer, Inc. <dev-feedback@writer.com>"]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-writer"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/writer"

[tool.poetry.dependencies]
python = ">=3.10,<4"
opentelemetry-api = "^1.38.0"
opentelemetry-instrumentation = ">=0.59b0"
opentelemetry-semantic-conventions = ">=0.59b0"
opentelemetry-semantic-conventions-ai = ">=0.4.11"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.0.0"
black = "^25.1.0"
isort = "^6.0.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
python-dotenv = "^1.1.1"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
pytest-asyncio = "^0.23.7"
opentelemetry-sdk = "^1.38.0"
writer-sdk = "^2.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["writer"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
writer = "opentelemetry.instrumentation.writer:WriterInstrumentor"
