[tool.coverage.run]
branch = true
source = ["opentelemetry/instrumentation/azure_search"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-azure-search"
version = "0.49.6"
description = "OpenTelemetry Azure AI Search instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Tomer Friedman <tomer@traceloop.com>",
  "Mahesh Babu Gorantla <maheshbabugorantla@gmail.com>",
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-azure-search"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/azure_search"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.38.0"
opentelemetry-instrumentation = ">=0.59b0"
opentelemetry-semantic-conventions = ">=0.59b0"
opentelemetry-semantic-conventions-ai = { path = "../opentelemetry-semantic-conventions-ai", develop = true }

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.0.0"
python-dotenv = "^1.2.1"

[tool.poetry.group.test.dependencies]
azure-search-documents = "^11.4.0"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
opentelemetry-sdk = "^1.38.0"
vcrpy = { version = ">=6.0.1", markers = "python_version >= '3.10'" }
pytest-recording = "^0.13.1"
pytest-asyncio = "^0.23.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["azure-search-documents"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
azure_search = "opentelemetry.instrumentation.azure_search:AzureSearchInstrumentor"
