[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/alephalpha" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-alephalpha"
version = "0.24.0"
description = "OpenTelemetry Aleph Alpha instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
  "Benedikt Wolf <bene25@web.de>",
]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-alephalpha"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/alephalpha"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.25.0"
opentelemetry-instrumentation = "^0.46b0"
opentelemetry-semantic-conventions = "^0.46b0"
opentelemetry-semantic-conventions-ai = "0.3.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.0.0"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
aleph_alpha_client = "^7.1.0"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
pytest-asyncio = "^0.23.7"
opentelemetry-sdk = "^1.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["aleph_alpha_client"] 

[tool.poetry.plugins."opentelemetry_instrumentor"]
aleph_alpha_client = "opentelemetry.instrumentation.alephalpha:AlephAlphaInstrumentor"
